export const studyTimes = [
  { value: "1 Hour" },
  { value: "1 Hour and 15 minutes" },
  { value: "1 Hour and 30 minutes" },
  { value: "1 Hour and 45 minutes" },
  { value: "2 Hour" },
  { value: "2 Hour and 15 minutes" },
  { value: "2 Hour and 30 minutes" },
  { value: "2 Hour and 45 minutes" },
  { value: "3 Hour" },
  { value: "3 Hour and 15 minutes" },
  { value: "3 Hour and 30 minutes" },
  { value: "3 Hour and 45 minutes" },
  { value: "5 Hour" },
  { value: "5 Hour and 15 minutes" },
  { value: "5 Hour and 30 minutes" },
  { value: "5 Hour and 45 minutes" },
  { value: "6 Hour" },
  { value: "6 Hour and 15 minutes" },
  { value: "6 Hour and 30 minutes" },
  { value: "6 Hour and 45 minutes" },
  { value: "7 Hour" },
  { value: "7 Hour and 15 minutes" },
  { value: "7 Hour and 30 minutes" },
  { value: "7 Hour and 45 minutes" },
  { value: "8 Hour" },
  { value: "8 Hour and 15 minutes" },
  { value: "8 Hour and 30 minutes" },
  { value: "8 Hour and 45 minutes" },
  { value: "9 Hour" },
  { value: "9 Hour and 15 minutes" },
  { value: "9 Hour and 30 minutes" },
  { value: "9 Hour and 45 minutes" },
  { value: "10 Hour" },
  { value: "10 Hour and 15 minutes" },
  { value: "10 Hour and 30 minutes" },
  { value: "10 Hour and 45 minutes" },
  { value: "11 Hour" },
  { value: "11 Hour and 15 minutes" },
  { value: "11 Hour and 30 minutes" },
  { value: "11 Hour and 45 minutes" },
  { value: "12 Hour" },
  { value: "12 Hour and 15 minutes" },
  { value: "12 Hour and 30 minutes" },
  { value: "12 Hour and 45 minutes" },
  { value: "13 Hour" },
  { value: "13 Hour and 15 minutes" },
  { value: "13 Hour and 30 minutes" },
  { value: "13 Hour and 45 minutes" },
  { value: "14 Hour" },
  { value: "14 Hour and 15 minutes" },
  { value: "14 Hour and 30 minutes" },
  { value: "14 Hour and 45 minutes" },
  { value: "15 Hour" },
  { value: "15 Hour and 15 minutes" },
  { value: "15 Hour and 30 minutes" },
  { value: "15 Hour and 45 minutes" },
  { value: "16 Hour" },
  { value: "16 Hour and 15 minutes" },
  { value: "16 Hour and 30 minutes" },
  { value: "16 Hour and 45 minutes" },
  { value: "17 Hour" },
  { value: "17 Hour and 15 minutes" },
  { value: "17 Hour and 30 minutes" },
  { value: "17 Hour and 45 minutes" },
  { value: "18 Hour" },
  { value: "18 Hour and 15 minutes" },
  { value: "18 Hour and 30 minutes" },
  { value: "18 Hour and 45 minutes" },
  { value: "19 Hour" },
  { value: "19 Hour and 15 minutes" },
  { value: "19 Hour and 30 minutes" },
  { value: "19 Hour and 45 minutes" },
  { value: "20 Hour" },
  { value: "20 Hour and 15 minutes" },
  { value: "20 Hour and 30 minutes" },
  { value: "20 Hour and 45 minutes" },
  { value: "21 Hour" },
  { value: "21 Hour and 15 minutes" },
  { value: "21 Hour and 30 minutes" },
  { value: "21 Hour and 45 minutes" },
  { value: "22 Hour" },
  { value: "22 Hour and 15 minutes" },
  { value: "22 Hour and 30 minutes" },
  { value: "22 Hour and 45 minutes" },
  { value: "I need help!" },
];
